oz2507/PHILIALE

register/check.php
register/signup.php
register/thanks.php

signup.php
check.php
thanks.php　を変更しました。
check.phpの頭のPHP文をコメントアウトしたままです。
すみません。

フレームワークを参考に枠組み修正

---

signout.php

signout.phpを追加してログアウト機能を追加

---

register/check.php
register/signup.php
register/thanks.html

登録処理を完成させた。
インデントを揃えた。
コメントアウトしておいた行を削除。
一応説明用のコメントを追加。
thanks.php→thanks.htmlに変更。

Complete register

---

Form/contact.html
assets/css/style_r.css
register/check.php
register/signup.php
register/thanks.html
signin.php

何度目か忘れましたが、今度こそ大丈夫かと、、、！<(_ _)>

imgのpathを修正

---

assets/css/top.css

toppageのcssを追加

---

assets/css/mypage.css
library2.php

ロゴの中央配置に成功

---

add_book.html
add_order.html
assets/css/style_r.css

すみません。CSS実装が完全に整ってませんが、一旦上げます。

本の詳細htmlを追加

---

mypage2.php
signin.php

signinの処理を完成させた。

---

detai_pop/detail.css
detai_pop/detail.html
detai_pop/detail.js

詳細のPOPをjsで作りました！

---

assets/css/style_r.css
detail.css
detail.html
detail.js
detail_pop.css

本の詳細POP完成しました！
本情報の取得、編集機能、削除機能の実装お願いします！

Complete detail

---

new_add_book/check_add_book.html
new_add_book/check_add_book_pop.css
new_add_book/new_add_book.css
new_add_book/new_add_book.html
new_add_book/new_add_book.js
new_add_book/new_add_book_pop.css

Pop create

---

detail_pop/future_detail.php
detail_pop/past_detail.php
mypage2.php

mypageに検索機能(sql等)
detail_popのdetail.htmlをdetail.phpへ変更。その後、past_detail.phpとfuture_detail.phpを同フォルダ下に作成。

mypageの検索機能

---

assets/css/mypage.css
detail_pop/past_detail.php
mypage2.php

mypage,librarynのbookカラムを調整

---

assets/css/style_r.css

cssフォーム崩れ再々修正

---

Form/policies.php
assets/css/mypage.css
assets/css/policies.css
assets/css/top.css
detail_pop/future_detail.php
detail_pop/past_detail.php
library2.php
movement.php
top.php

読みたいから読んだへ

---

Form/check.php
Form/contact.php
Form/thanks.php
absorb/absorb.php
absorb/check.php
absorb/submit.php
future_edit.php
insert_future.php
insert_past.php
into_library.php
library2.php
movement.php
mypage2.php
past_edit.php
register/check.php
register/signup.php

自分が関与したページの動作及びインデントの確認完了

---

alert.js
detail_pop/past_detail.php
mypage2.php

とりあえずのアラートを追加

---

assets/css/style_r.css
pop_pages/add_order.html
pop_pages/delete_alart.html

Add delete_alart.html

---

mypage2.php
new_add_book/new_add_book.css
new_add_book/new_add_book.js
new_add_book/new_add_book_future.php
new_add_book/new_add_book_past.php
new_add_book/new_add_book_pop.css

新規追加のjs実装（若干崩れてるけど）

---

absorb/check.php
absorb/submit_2.php
detail_pop/detail.css
detail_pop/future_detail.js
detail_pop/future_detail.php
detail_pop/past_detail.js
detail_pop/past_detail.php

Complete absorb2

---

absorb/check.php

absorbの表示修正

---

Form/contact.php

お問合せページ、$_SESSIONが空の際のデバッグ

---

pop_pages/past_add_book.php

初めての追加に合わせた

---

assets/css/result_search.css
pop_pages/past_add_book.php
search_books/result_search.php
title_search.php

タイトル検索画面のUI

---

search_books/result_search.php
title_search.php

バリデーションやーと終わった

---

assets/css/result_search.css
assets/css/style_re.css
search_books/insert.php
search_books/result_search.php

タイトル通り。
再検索後のUIはまだ直ってない。
追加はできてる。
インデント整えた。

本の再検索と呼んだへ追加

---

assets/css/mypage.css
mypage2.php
new_add_book/add_future_book.js
new_add_book/new_add_book_future.css
new_add_book/new_add_book_past.css
new_add_book/new_add_book_past.php
partial/js.php

読みたいのjs表示に成功
